### ISSUE TITLE
The extension is disabled in a remote web based vscode

### ISSUE THREAD

**Issue by takikadiri** [mamba-org/vscode-micromamba#26]
Thank you for your efforts ! Making micromamba and vscode working well together is something that i'm looking for. Unfortunately i have a web based remote vscode installation ( i use [code-server](https://github.com/coder/code-server)), and apparently the extension does only support Desktop based install of vscode, when installing the extension, i get this message :

> This extension is disabled because it is defined to run only in code-server for the desktop

Do you plan to support remote vscode install ?

**Comment by corker** [comment]
Great to hear that you like the extension. I'm limited in time as I'm the only maintainer of the extension. I don't have plans to test in remote installation, and I don't know if it would work.
