### ISSUE TITLE
Logs during micromamba env creation

### ISSUE THREAD

**Issue by minghao51** [mamba-org/vscode-micromamba#35]
First of all, this is an awesome extension to setup multiple micromamba env.

Just wondering, is there a way to view the logs/verbose scripts debug during the creation of environments?

- It seems to fail without any obvious prompts when there are errors in the environment.yaml (unresolvable/wrong version setup etc)
- And would (at times) take quite a bit of time during setup (perhaps due to mixing micromamba + various pip packages on my side)

**Comment by corker** [comment]
Thank you for the kind words. My goal is to make developers life easier. It's possible to see the micromamba logs. You could open the output pane and select micromamba as a source.

**Comment by corker** [comment]
I'll check if it's possible to add a button to the error notification to open the output pane

**Comment by corker** [comment]
Show output command added in v0.1.18
