### ISSUE TITLE
does not work on Windows

### ISSUE THREAD

**Issue by estkae** [mamba-org/vscode-micromamba#38]
It does not work at all with windows. With creating an Env. no list of possible types comes. I can not enter the name of the Env. Unusable

Windows 11
Powershell
Latest Micromamba

**Comment by corker** [comment]
Hi @estkae thank you for reporting the problem. What are the steps to reproduce the problem and the output from the VSCode output panel?
<img width="1229" alt="image" src="https://github.com/mamba-org/vscode-micromamba/assets/2121276/b821113a-d3b0-4ba1-adec-f990bb2c57fa">
