### ISSUE TITLE
Micromamba Extension not respecting `.condarc` file

### ISSUE THREAD

**Issue by ThomasMarwitzQC** [mamba-org/vscode-micromamba#42]
### Environment

1. `node -v`: -
1. `npm -v`: -
1. Operating system: OSX Sonoma 14.1.1

### Prerequisite
I already have a `environment.yml` file that contains some packages that are only available through our intern channel. The configuration to access this channel is specified in `~/.condarc`. When activating the environment, an error occurred stating the intern channel could not be found. 

### Expected Behavior
I would expect the extension to allow for a global configuration like `~/.condarc`.

### Actual Behavior
I didn't find a setting where I could set a global configuration file. Is there something I've missed?

**Comment by corker** [comment]
Initially, my thinking was to isolate local micromamba from the global configuration to make sure behavior is the same on all dev machines. I just released a new version, 0.1.20, with enabled rc file resolution and environment variables.
Please see the micromamba docs for rc file usage https://mamba.readthedocs.io/en/latest/user_guide/configuration.html
