### ISSUE TITLE
Creating the environment fails with 

### ISSUE THREAD

**Issue by rawlik** [mamba-org/vscode-micromamba#53]
### Environment

1. `node -v`: none
1. `npm -v`: none
1. Operating system: linux

### Prerequisite
VSCode with micromamba

### Steps to Reproduce
Create a minimal `environment.yml` file:
```yaml
channels:
  - conda-forge
dependencies:
  - python
```

And create an environment with vscode-micromamba.

### Expected Behavior

The environment is created with a "default" name or otherwise an error message informs the user that "name" has to be defined in the `environment.yml` file.

### Actual Behavior

Micromamba extension will fail to create an environment and provide no useful error message.

**Comment by corker** [comment]
fixed with v0.1.23
