### ISSUE TITLE
The plugin does not download the correct micromamba executable for arm/aarch64

### ISSUE THREAD

**Issue by vanem** [mamba-org/vscode-micromamba#54]
### Environment
Operating system: Linux rpi5-2CCF6726E2E4 6.6.31+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux

### Prerequisite

Vscode remote SSH on Raspberry Pi 5
Install vscode-micromamba on remote
Empty repo

### Steps to Reproduce

Micromamba: create environment

### Relevant Debug Info

`1: Syntax error: Unterminated quoted string`

### Expected Behavior

Micromamba environment created successfully

### Actual Behavior

Create environment fails with error

--- 

The plugin seems to download micromamba executable for the wrong architecture. If I download manually `micromamaba` in `.micromamba` folder, and invoke environment creation, it completes successfully and works as expected.
For reference, I downloaded manually the release for aarch64: `https://github.com/mamba-org/micromamba-releases/releases/download/1.5.9-1/micromamba-linux-aarch64`
Officially there is also this script available to automate the download and install of `micromamba` for the correct architecture, that can be invoked like this:
`"${SHELL}" <(curl -L https://micro.mamba.pm/install.sh)`

**Comment by corker** [comment]
Please check v0.1.24 and report

**Comment by vanem** [comment]
> Please check v0.1.24 and report

Thank you, I can confirm it works, the correct version of micromamba was downloaded by the plugin on environment creation:
`.micromamba/micromamba: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, stripped`
