### ISSUE TITLE
[feature request] Let user decide global home directory 

### ISSUE THREAD

**Issue by peiqingj** [mamba-org/vscode-micromamba#55]
In most cases, the users already have a working env installed in global home directory, e.g. /home/user/micromamba, which is the default micromamba home officially.
It would be great to allow the user to setup the path to global home directory. 
The mismatching of global home directory stops the extension from activating env in vscode terminal.

**Comment by corker** [comment]
Thank you for the request, @peiqingj. The primary use case I had in mind for this extension is to allow developers to define tools they need for a project in an environment.yml file, and the extension could create a virtual environment and activate it for the user without knowing much about micromamba. All dependencies, like micromamba, packages, etc., could be stored inside the project-specific location (.micromamba) or in a global shared directory.

<img width="691" alt="image" src="https://github.com/user-attachments/assets/ec213aa4-04c4-4b3b-8bf7-7f32bdf474bd">

In this setup, the extension doesn't interfere with the global micromamba installation - when it exists.

Can you describe your use case so we can find an excellent way to integrate it and make it fit nicely with the original use case?

Have you tried the "Micromamba: activate environment by path" command? Is it what you are looking for?

**Comment by corker** [comment]
Please reopen if it's still relevant
