### ISSUE TITLE
Please add support for MAMBA_ROOT_PREFIX

### ISSUE THREAD

**Issue by vx-i** [mamba-org/vscode-micromamba#7]
### Environment

1. `node -v`: --
1. `npm -v`: --
1. Operating system: Windows 10 Pro

### Prerequisite

--

### Steps to Reproduce

Micromamba: activate environment

### Expected Behavior

"Micromamba: activate environment" should check if MAMBA_ROOT_PREFIX is set and use it

### Actual Behavior

"Micromamba: create environment" needs to be used

--- 

Hi corker, I saw in #3 that you plan to work on this feature. Do you have a rough schedule of when you will have time for it? Unfortunately, I am not familiar with TypeScript, so I cannot help out with a pull request.

**Comment by corker** [comment]
That shouldn't be a big deal to implement it. I'm going to take a look in February 2022

**Comment by corker** [comment]
I found the problem. Global and local micromamba environment variables were mixed.
When micromamba is already in the path the extension didn't download the local version but tried to use the global.
At the same time MAMBA_ROOT_PREFIX and MAMBA_EXE were set to the local path and confused the global micromamba.
I change the logic download the local micromamba when it isn't downloaded yet. This way extension never relies on the global micromamba.
